commented some parts

diff --git a/.github/workflows/acceptance-tests.yml b/.github/workflows/acceptance-tests.yml
--- a/.github/workflows/acceptance-tests.yml
+++ b/.github/workflows/acceptance-tests.yml
@@ -60,40 +60,40 @@ jobs:
           INPUT_WORKFLOW_FILE_NAME: release.yml
           INPUT_REF: main
           INPUT_REPO: homebrew-brew
-      - name: Global - Testing installation of Twilio CLI (1)
-        if: ${{ github.respository != 'twilio/draft-release-branch' }}
-        env:
-          REPO_NAME: ${{ github.repository_owner }}
-        run: |
-          brew tap $REPO_NAME/brew && brew install twilio
-          .github/scripts/cmds-to-test.sh
-      - name: Global - Testing upgrade Twilio CLI (2)
-        if: ${{ github.respository != 'twilio/draft-release-branch' }}
-        env:
-          REPO_NAME: ${{ github.repository_owner }}
-        run: |
-          brew tap $REPO_NAME/brew && brew install twilio
-          brew upgrade twilio
-          .github/scripts/cmds-to-test.sh
-      - name: Draft - Testing installation of Twilio CLI (1)
-        if: ${{ github.respository == 'twilio/draft-release-branch' }}
-        env:
-          REPO_NAME: ${{ github.repository_owner }}
-        run: |
-          brew tap $REPO_NAME/brew && brew install twiliodraft
-          .github/scripts/cmds-to-test.sh
-      - name: Draft - Testing upgrade Twilio CLI (2)
-        if: ${{ github.respository == 'twilio/draft-release-branch' }}
-        env:
-          REPO_NAME: ${{ github.repository_owner }}
-        run: |
-          brew tap $REPO_NAME/brew && brew install twiliodraft
-          brew upgrade twilio
-          .github/scripts/cmds-to-test.sh
-      - name: setup brew failure output
-        if: failure() || cancelled()
-        id: failure_brew
-        run: echo '::set-output name=FAILURE_TAG_BREW::true'
+      # - name: Global - Testing installation of Twilio CLI (1)
+      #   if: ${{ github.respository != 'rohith-prakash/draft-release-branch' }}
+      #   env:
+      #     REPO_NAME: ${{ github.repository_owner }}
+      #   run: |
+      #     brew tap $REPO_NAME/brew && brew install twilio
+      #     .github/scripts/cmds-to-test.sh
+      # - name: Global - Testing upgrade Twilio CLI (2)
+      #   if: ${{ github.respository != 'rohith-prakash/draft-release-branch' }}
+      #   env:
+      #     REPO_NAME: ${{ github.repository_owner }}
+      #   run: |
+      #     brew tap $REPO_NAME/brew && brew install twilio
+      #     brew upgrade twilio
+      #     .github/scripts/cmds-to-test.sh
+      # - name: Draft - Testing installation of Twilio CLI (1)
+      #   if: ${{ github.respository == 'rohith-prakash/draft-release-branch' }}
+      #   env:
+      #     REPO_NAME: ${{ github.repository_owner }}
+      #   run: |
+      #     brew tap $REPO_NAME/brew && brew install twiliodraft
+      #     .github/scripts/cmds-to-test.sh
+      # - name: Draft - Testing upgrade Twilio CLI (2)
+      #   if: ${{ github.respository == 'twilio/draft-release-branch' }}
+      #   env:
+      #     REPO_NAME: ${{ github.repository_owner }}
+      #   run: |
+      #     brew tap $REPO_NAME/brew && brew install twiliodraft
+      #     brew upgrade twilio
+      #     .github/scripts/cmds-to-test.sh
+      # - name: setup brew failure output
+      #   if: failure() || cancelled()
+      #   id: failure_brew
+      #   run: echo '::set-output name=FAILURE_TAG_BREW::true'
 
   wait-for-windows-releases:
     name: Wait for windows platform executables Release to complete
@@ -110,24 +110,24 @@ jobs:
         env:
           INPUT_WORKFLOW_FILE_NAME: windows-executable-release.yml
           INPUT_REF: ${{ needs.get-branch.outputs.branch }}
-      - name: Perform acceptance install and tests on Windows
-        id: windows_acceptance_run
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release download ${{ needs.get-tag.outputs.TAG_NAME }} --pattern '*.exe'
-          ls
-          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
-          ./scoop.ps1 -RunAsAdmin
-          scoop install gsudo
-          ./twilio-${{ needs.get-tag.outputs.TAG_NAME }}.exe /S
-          sleep 100
-          $env:Path += ";C:\Program Files (x86)\twilio-cli\bin"
-          $Env:Path
-          cd C:\"Program Files (x86)\twilio-cli"
-          dir
-          twilio --version
-          twilio api --help
+      # - name: Perform acceptance install and tests on Windows
+      #   id: windows_acceptance_run
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     gh release download ${{ needs.get-tag.outputs.TAG_NAME }} --pattern '*.exe'
+      #     ls
+      #     (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
+      #     ./scoop.ps1 -RunAsAdmin
+      #     scoop install gsudo
+      #     ./twilio-${{ needs.get-tag.outputs.TAG_NAME }}.exe /S
+      #     sleep 100
+      #     $env:Path += ";C:\Program Files (x86)\twilio-cli\bin"
+      #     $Env:Path
+      #     cd C:\"Program Files (x86)\twilio-cli"
+      #     dir
+      #     twilio --version
+      #     twilio api --help
       - name: setup windows failure output
         if: failure() || cancelled()
         id: failure_windows
@@ -148,20 +148,20 @@ jobs:
         env:
           INPUT_WORKFLOW_FILE_NAME: macos-executable-release.yml
           INPUT_REF: ${{ needs.get-branch.outputs.branch }}
-      - name: Perform acceptance install and test on binaries
-        id: macos_acceptance_run
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release download ${{ needs.get-tag.outputs.TAG_NAME }} --pattern '*.pkg'
-          sudo installer -pkg twilio-${{ needs.get-tag.outputs.TAG_NAME }}.pkg -target ~/
-          ls
-          twilio --version
-          twilio api --help
-      - name: setup macos failure output
-        if: failure() || cancelled()
-        id: failure_macos
-        run: echo '::set-output name=FAILURE_TAG_MACOS::true'
+      # - name: Perform acceptance install and test on binaries
+      #   id: macos_acceptance_run
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     gh release download ${{ needs.get-tag.outputs.TAG_NAME }} --pattern '*.pkg'
+      #     sudo installer -pkg twilio-${{ needs.get-tag.outputs.TAG_NAME }}.pkg -target ~/
+      #     ls
+      #     twilio --version
+      #     twilio api --help
+      # - name: setup macos failure output
+      #   if: failure() || cancelled()
+      #   id: failure_macos
+      #   run: echo '::set-output name=FAILURE_TAG_MACOS::true'
 
   wait-for-debian-releases:
     name: Wait for debian platform executables Release to complete
@@ -207,77 +207,77 @@ jobs:
         env:
           INPUT_WORKFLOW_FILE_NAME: apt-release.yml
           INPUT_REF: ${{ needs.get-branch.outputs.branch }}
-      - name: Perform acceptance install and test on apt package 
-        id: apt_acceptance_run
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          wget -qO- https://twilio-cli-prod.s3.amazonaws.com/twilio_pub.asc | sudo apt-key add - 
-          sudo touch /etc/apt/sources.list.d/twilio.list
-          echo 'deb https://twilio-cli-prod.s3.amazonaws.com/apt/ /' | sudo tee /etc/apt/sources.list.d/twilio.list
-          sudo apt update
-          sudo apt install -y twilio
+      # - name: Perform acceptance install and test on apt package 
+      #   id: apt_acceptance_run
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     wget -qO- https://twilio-cli-prod.s3.amazonaws.com/twilio_pub.asc | sudo apt-key add - 
+      #     sudo touch /etc/apt/sources.list.d/twilio.list
+      #     echo 'deb https://twilio-cli-prod.s3.amazonaws.com/apt/ /' | sudo tee /etc/apt/sources.list.d/twilio.list
+      #     sudo apt update
+      #     sudo apt install -y twilio
 
-          ls
-          twilio --version
-          twilio api --help
-          .github/scripts/cmds-to-test.sh
-      - name: APT upgrade twilio package
-        run: |
-          sudo apt-get install --only-upgrade twilio
-          .github/scripts/cmds-to-test.sh
-      - name: APT downgrade twilio package
-        run: |
-          sudo apt-get install -y twilio=3.1.0-1 --allow-downgrades
-          twilio --version
-          .github/scripts/cmds-to-test.sh
+      #     ls
+      #     twilio --version
+      #     twilio api --help
+      #     .github/scripts/cmds-to-test.sh
+      # - name: APT upgrade twilio package
+      #   run: |
+      #     sudo apt-get install --only-upgrade twilio
+      #     .github/scripts/cmds-to-test.sh
+      # - name: APT downgrade twilio package
+      #   run: |
+      #     sudo apt-get install -y twilio=3.1.0-1 --allow-downgrades
+      #     twilio --version
+      #     .github/scripts/cmds-to-test.sh
 
-      - name: setup apt failure output
-        if: failure() || cancelled()
-        id: failure_apt
-        run: echo '::set-output name=FAILURE_TAG_APT::true'
-  test-npm-releases:
-    name: NPM acceptance testing
-    runs-on: ubuntu-latest
-    continue-on-error: true
-    outputs:
-      ACCEPTANCE_FAILURE_TAG: ${{ steps.failure_npm.outputs.FAILURE_TAG_NPM }}
-    strategy:
-      matrix:
-        node-version: [ 16.x, 14.x, 10.x, 12.x ]
-    steps:
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/checkout@v2
-        with:
-          node-version: ${{ matrix.node-version }}
-      - name: Check for cached twilio installation
-        run: |
-          if ! command -v twilio > /dev/null; then twilio() { printf '%sCLI is not installed, all good. '; } else echo "CLI is installed already, Abort."; exit 1; fi
-          twilio --version
-      - name: Node Install - Testing installation of Twilio CLI (1)
-        if: ${{ github.respository != 'twilio/draft-release-branch' }}
-        run: |
-          npm install -g twilio-cli
-          .github/scripts/cmds-to-test.sh
-      - name: NPM Update - Testing upgrade Twilio CLI (2)
-        if: ${{ github.respository != 'twilio/draft-release-branch' }}
-        run: |
-          npm update -g twilio-cli
-          .github/scripts/cmds-to-test.sh
-      - name: Node Install - Testing installation of Twilio CLI (1)
-        if: ${{ github.respository == 'twilio/draft-release-branch' }}
-        run: |
-          npm install -g twilio-cli@$(npm view twilio-cli dist-tags.draft-release-branch)
-          .github/scripts/cmds-to-test.sh
-      - name: NPM Update - Testing upgrade Twilio CLI (2)
-        if: ${{ github.respository == 'twilio/draft-release-branch' }}
-        run: |
-          npm update -g twilio-cli@$(npm view twilio-cli dist-tags.draft-release-branch)
-          .github/scripts/cmds-to-test.sh
-      - name: setup debian failure output
-        if: failure() || cancelled()
-        id: failure_npm
-        run: echo '::set-output name=FAILURE_TAG_NPM::true'
+      # - name: setup apt failure output
+      #   if: failure() || cancelled()
+      #   id: failure_apt
+      #   run: echo '::set-output name=FAILURE_TAG_APT::true'
+  # test-npm-releases:
+  #   name: NPM acceptance testing
+  #   runs-on: ubuntu-latest
+  #   continue-on-error: true
+  #   outputs:
+  #     ACCEPTANCE_FAILURE_TAG: ${{ steps.failure_npm.outputs.FAILURE_TAG_NPM }}
+  #   strategy:
+  #     matrix:
+  #       node-version: [ 16.x, 14.x, 10.x, 12.x ]
+  #   steps:
+  #     - name: Use Node.js ${{ matrix.node-version }}
+  #       uses: actions/checkout@v2
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #     - name: Check for cached twilio installation
+  #       run: |
+  #         if ! command -v twilio > /dev/null; then twilio() { printf '%sCLI is not installed, all good. '; } else echo "CLI is installed already, Abort."; exit 1; fi
+  #         twilio --version
+  #     - name: Node Install - Testing installation of Twilio CLI (1)
+  #       if: ${{ github.respository != 'twilio/draft-release-branch' }}
+  #       run: |
+  #         npm install -g twilio-cli
+  #         .github/scripts/cmds-to-test.sh
+  #     - name: NPM Update - Testing upgrade Twilio CLI (2)
+  #       if: ${{ github.respository != 'twilio/draft-release-branch' }}
+  #       run: |
+  #         npm update -g twilio-cli
+  #         .github/scripts/cmds-to-test.sh
+  #     - name: Node Install - Testing installation of Twilio CLI (1)
+  #       if: ${{ github.respository == 'twilio/draft-release-branch' }}
+  #       run: |
+  #         npm install -g twilio-cli@$(npm view twilio-cli dist-tags.draft-release-branch)
+  #         .github/scripts/cmds-to-test.sh
+  #     - name: NPM Update - Testing upgrade Twilio CLI (2)
+  #       if: ${{ github.respository == 'twilio/draft-release-branch' }}
+  #       run: |
+  #         npm update -g twilio-cli@$(npm view twilio-cli dist-tags.draft-release-branch)
+  #         .github/scripts/cmds-to-test.sh
+  #     - name: setup debian failure output
+  #       if: failure() || cancelled()
+  #       id: failure_npm
+  #       run: echo '::set-output name=FAILURE_TAG_NPM::true'
 
   test-scoop-release:
     name: Do scoop testing after release
@@ -296,31 +296,31 @@ jobs:
           INPUT_OWNER: ${{ github.repository_owner }}
           INPUT_REPO: scoop-twilio-cli
           INPUT_GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
-      - name: Perform testing on scoop installations
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
-          ./scoop.ps1 -RunAsAdmin
-          scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
-          scoop install twilio
-          twilio --version
-          twilio api --help
-      - name: Draft - Perform testing on scoop installations
-        if: ${{ github.respository == 'twilio/draft-release-branch' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-           (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
-           ./scoop.ps1 -RunAsAdmin
-           scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
-           scoop install twiliodraft
-           twilio --version
-           twilio api --help
-      - name: setup scoop failure output
-        if: failure() || cancelled()
-        id: failure_scoop
-        run: echo '::set-output name=FAILURE_TAG_SCOOP::true'
+      # - name: Perform testing on scoop installations
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
+      #     ./scoop.ps1 -RunAsAdmin
+      #     scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
+      #     scoop install twilio
+      #     twilio --version
+      #     twilio api --help
+      # - name: Draft - Perform testing on scoop installations
+      #   if: ${{ github.respository == 'twilio/draft-release-branch' }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #      (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
+      #      ./scoop.ps1 -RunAsAdmin
+      #      scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
+      #      scoop install twiliodraft
+      #      twilio --version
+      #      twilio api --help
+      # - name: setup scoop failure output
+      #   if: failure() || cancelled()
+      #   id: failure_scoop
+      #   run: echo '::set-output name=FAILURE_TAG_SCOOP::true'
 
   notify-complete-fail:
     needs: [wait-for-brew-releases, wait-for-windows-releases, wait-for-debian-releases, wait-for-macos-releases, test-scoop-release, test-npm-releases, test-apt-release]
